### ISSUE TITLE
Two questions about the test module

### ISSUE THREAD

**Issue by tayei1997** [podofo/podofo#132]
Hi, I have two questions about the test module  (podofo v 0.10.2)

1. I run the test under VS, and it seems that only the test code in test/unit is executed, while the code under ContentParser and other files is not executed, and I observe the ContentParser.cpp, and I found that it seems to refer to a non-existing class " PdfContentsTokenizer". Is it possible that the test code other than UNIT is outdated?

2. I downloaded the resource files needed for the tests under exten, and ran the tests for unit, the result was "117 passed | 6 failed", 
The failed test case reports an error:
"... \... \... \test\unit\PageTreeTest.cpp(102): FAILED.
explicitly with message.
  Coult not find Arial font"
There is no Arial in the downloaded Fonts folder.

**Comment by ceztko** [comment]
1) Non automatic tests were removed in master, that means all tests not in `unit` folder.
2) Master also searches for "LiberationSans" instead of "Arial", to not incur in missing fonts.

If you want to backport 2) fix to unit tests in [0.10.x](https://github.com/podofo/podofo/tree/0.10.x) (we are now at stable 0.10.3, with 0.10.4-dev), supply a patch to that branch.
