### ISSUE TITLE
legacy.dll not copied

### ISSUE THREAD

**Issue by NieLuc** [podofo/podofo#135]
* **I'm submitting a:**
  - [ ] Vulnerability report -> **use the specific [form](https://github.com/podofo/podofo/security/advisories/new) instead!**
  - [x] Bug report
  - [ ] Feature request/suggestion

* **[Bug report] What is the current behavior?**
* When I execute my application on my dev machine, all is working. When I deploy this app on my target machine, I get an error "The application was unable to start correctly (0xc0000142)".

The openSSL libcrypto-3-x64.dll library rely on legacy.dll, which seems to be linked with the absolute path of my vcpkg installation on my development computer (DW give me the exact path of legacy.dll on my dev computer) ! If I recreate on my target computer the exact path of legacy.dll on my development computer, my app run !

* **[Bug report] What is the expected behavior?**
Library gets copied into the build folder and project is linked to this library

* **[Bug report] Please provide the steps to reproduce and if possible a minimal reproduction code of the problem**
Try to deploy podofo on a Computer without vcpkg installed.

* **Please tell us about your environment:**
  
  - Version/git revision: [1.10.0]
  - Operating System: Windows (64 bits)
  - Package manager used: vcpkg

I dont know if this error is based on the podofo cmake configuration or is within vcpkg.

**Comment by as-ascii** [comment]
Encountered similar problem with vcpkg installation.
As a workaround try to set OPENSSL_MODULES environment variable like here:
https://github.com/docwire/docwire/pull/92/commits/b3a04e45688d56c9f46d96c5b3f271297f3dab97
legacy.dll is installed via openssl vcpkg port that is required by podofo vcpkg port, but it is inside ossl-modules subdirectory so it can be invisible according to $PATH (on Windows) or $LD_LIBRARY_PATH (on Linux).

**Comment by NieLuc** [comment]
The OPENSSL_MODULES path is the path to the OPENSSL libs installed via vcpkg? Or does this dictate the path where to install the OPENSSL_MODULES?

**Comment by ceztko** [comment]
PoDoDo specify its dependency to OpenSSL on the `CMakeLists.txt` by the following few directives:

```
find_package(OpenSSL REQUIRED)
# ...
set(PODOFO_LIB_DEPENDS OpenSSL::SSL)
```

Unless there is a better way to specify that PoDoFo needs the legacy providers (and it doesn't appear there's one at the [moment](https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/FindOpenSSL.cmake?ref_type=heads#L1)), the issue you have is with deployment of vcpkg dependencies.

> The OPENSSL_MODULES path is the path to the OPENSSL libs installed via vcpkg?

It seems a OpenSSL project specific runtime setting, so I guess yes. There may be some vcpkg settings so that the modules are copied among the main OpenSSL runtime components, but I don't use vcpkg so I don't know. You may have scripts to fix the deployment of the dependencies as part of your development workflow, which is also a common practice when things don't work out of the box. If you think there's a way where PoDoFo or OpenSSL vcpkg ports could be improved please refer to them, as I don't have control on them, but feel free to continue the discussion here for workarounds.

**Comment by as-ascii** [comment]
This is the initial discussion about this issue on vcpkg website:
https://github.com/microsoft/vcpkg/discussions/36715
You can join, maybe someone have better solution.

**Comment by as-ascii** [comment]
I can see now that your problem might be closely related but not exactly the similar. You can try to set OPENSSL_MODULES environment variable to path where the legacy.dll is stored and then run the problematic application but if absolute path is embedded into libcrypto.dll I am not sure if it will help.

**Comment by NieLuc** [comment]
Okay, now this works for me. But I dont like to set environment variables on my target machine at least not permanent. Is there a way to build it so that you dont have to do that?

**Comment by ceztko** [comment]
I guess today RC4 is not that required, so I stopped eagerly throwing on missing RC4. See https://github.com/podofo/podofo/commit/fb36f86cb7cc1313669e432ff793e170f981e272.
