### ISSUE TITLE
Let discuss about fonts in PoDoFo 0.10.0

### ISSUE THREAD

**Issue by igormironchik** [podofo/podofo#14]
Hello,

I use `PoDoFo` 0.9.8 in one my pet project, I see that you merged `pdfmm` into `PoDoFo` and now it's 0.10.0 version, and API incompatible with previous version. OK, I decided to make a branch of my project and switch into `PoDoFo` 0.10.0.

What I figured out is `PdfFont` metrics for concrete font can be obtained after setting font to `PdfPainter` with actual size. Oh, uh, this is very-very unusable. Metrics of the font uses to calculate a lot of stuff during creating PDF from scratch. Very often I need to create two different fonts and obtain them metrics for some calculations, and only after set some font to painter and do drawing, what impossible with the new API.

So, could you consider ability for obtaining metrics of the font without setting him to painter?

Thanks.

**Comment by ceztko** [comment]
I am not sure I understand. An instance of `PdfFontMetrics` metrics can be obtained from the font with `PdfFont::GetMetrics()`, which returns immutable metrics. Maybe you are referring to the old [`PdfFont::GetFontSize()`](https://github.com/podofo/podofo/blob/0.9.x/src/podofo/doc/PdfFont.h#L102) or others? If so, that won't come back: `PdfFont` is now immutable object in the public API, and that for good reasons, and the only metrics that it returns are immutable. The text state parameters such as `FontSize`, `FontScale`, etc. they are not semantically part of the font (which is now stateless), but stateful parameters. If you referred to these, you'll have to think out of the box and solve the issue in a different way. You can also show me (please, short) snippets of the code to explain me what you were doing previously.

**Comment by ceztko** [comment]
I also want to  add that at some point I want to add full inspectable text/graphics state in the `PdfPainter`. That's in my TODO list. I am not sure it can help in what you want to achieve, though.

**Comment by igormironchik** [comment]
For example some old code:

```cpp
PdfFont * textFont = createFont( "Arial", false /* bold */, false /* italic */, 30.0 /* size */ );

PdfFont * font = createFont( "Droid Serif", false, false, 20.0 );

double s = 0.0;

if( something )
	s = font->GetFontMetrics()->StringWidth( PdfString( " " ) );
else
	s = textFont->GetFontMetrics()->StringWidth( PdfString( " " ) );
```

Where `createFont()` is my auxiliary function to create concrete `PdfFont` with concrete font size.

So, how can I measure space width with some dependencies on different fonts?

**Comment by ceztko** [comment]
> For example some old code:

That's more understandable. Now, the new API to compute string metrics is `PdfFont::GetStringLength(str, textstate)`. For example:

```
    PdfTextState state;
    state.FontSize = 18;
    font.GetStringLength("string", state);
```

Font size is not gonna back to ```PdfFont``` as a mutable member anymore, because it was a fragile design choice: now the `PdfFont` class specific public APIs represent an immutable object, as found on the PDF (under the hood there's a mutable state, but it's a technical one neeeded to create the final `/Encoding`, not related to PDF specification). Font size and others becomes context/state parameter, which you must supply when computing string widths. Also consider that what returned by `GetStringLength` is unscaled with respect to CTM (Current Translation Matrix). This is the same behavior as it was in 0.9.x.

> OK. But provide public API to receive PdfFontMetrics for concrete PdfFont with concrete parameters, like font size.

Such request doesn't make much sense in this form, but I hope what you need is answered above. If so, please close the issue.

**Comment by igormironchik** [comment]
Agreed, `PdfTextState` with conjunction with `PdfFont` solves, I guess, all my issues. Thanks and Sorry for your time.
