### ISSUE TITLE
Segmentation fault when trying to Load image

### ISSUE THREAD

**Issue by NieLuc** [podofo/podofo#141]
* **I'm submitting a:**
  - [ ] Vulnerability report -> **use the specific [form](https://github.com/podofo/podofo/security/advisories/new) instead!**
  - [x] Bug report
  - [ ] Feature request/suggestion

* **[Bug report] What is the current behavior?**
SIGSEV when trying to load image

* **[Bug report] What is the expected behavior?**
It works

* **[Bug report] Please provide the steps to reproduce and if possible a minimal reproduction code of the problem**
`        PdfPainter painter;
        auto pdfImage = document.CreateImage();
        qDebug() << "imagepath" << pictureDir;
        pdfImage->Load(pictureDir.toStdString());
        painter.DrawImage( *pdfImage.get(), 50.0, 50.0 );

        painter.FinishDrawing();`

* **Please tell us about your environment:**
  
  - Version/git revision: [1.10.0]
  - Operating System:[Windows (32/64 bits)]
  - Package manager used: [vcpkg]

* **[Bug report/Feature request] Other information**

  E.g. sample PDF documents, stacktraces, related issues, links for us to have contex, suggestions how to fix, etc.

**Comment by ceztko** [comment]
Don't assume your failures can be easily reproduced: attach the image you were trying to load.

**Comment by NieLuc** [comment]
Oh okay, sorry. Here is the image i wanted to load (it doesnt work with any picture I have tried).
I have also included a picture of the debugger I dont know if that helps.

Do you have paypal for a little tip?
![SIGSEVLoadPng](https://github.com/podofo/podofo/assets/141717827/5f682799-5c42-4aa3-9ca3-0db409dde2e8)
![Screenshot 2023-10-19 154846](https://github.com/podofo/podofo/assets/141717827/2d8c5bb4-6291-4eb9-a663-6ca8c1cf7a4f)

**Comment by NieLuc** [comment]
I also found out that the client data of the ctx object is a Qt Object, can this be the cause of the error?
![DebuggingctxInfo](https://github.com/podofo/podofo/assets/141717827/4ee9fa75-22af-4120-ad82-fd3c6a53b4fe)

**Comment by ceztko** [comment]
Please, don't put in the equation Qt stuff: I don't use Qt, and I can't give you support for that API. `PdfImage::Load(const std::string_view& filepath)` accepts a file path: ensure what you are passing to that function is a valid file path where the image is stored. I have no issues at all with the following code with the image you attached.

```
    PdfMemDocument document;
    auto pdfImage = document.CreateImage();
    pdfImage->Load(R"(D:\310401373-2d8c5bb4-6291-4eb9-a663-6ca8c1cf7a4f.png)");
```

I'm noticing you are using an old PoDoFo version, ensure you are using the latest official release 0.10.3 (it's not in my control if vcpkg still hasn't packaged it). I'm closing the issue now: if you still can't sort things for you, clone the 0.10 branch and try to reproduce it in the PoDoFo [playground](https://github.com/podofo/podofo/tree/0.10.x/playground), to rule out the issue is in PoDoFo at all (which I don't believe, at the moment). Instead, if you can reproduce an issue in the playground, feel free to re-open.
