### ISSUE TITLE
FT_Load_Sfnt_Table, the judgment of return value

### ISSUE THREAD

**Issue by dzm0120** [podofo/podofo#150]
[Bug report]
In the function tryExtractDataFromTTC(), at line 185, the return value should be judged "rc != 0".
FreeType error code, 0 means success.
https://freetype.org/freetype2/docs/reference/ft2-truetype_tables.html#ft_load_sfnt_table

**Comment by ceztko** [comment]
Thanks. TTC support was added in #101 but it's strange: the code hasn't been changed since. For sure I tested it but in the end some bad code was committed instead. Unfortunately it wasn't unit tested so everything could have happened. I added a unit test with a custom TTC font. I found out that some TTC fonts are Type1 CFF (also known as OpenType CFF, see the first note at this [link ](https://helpx.adobe.com/fonts/kb/postscript-type-1-fonts-end-of-support.html)), but unfortunately subset is not supported for those yet.
