### ISSUE TITLE
Make some of the functions of PDFImage public

### ISSUE THREAD

**Issue by sfirouz** [podofo/podofo#166]
- [x] Feature request/suggestion
> 
> * **[Feature request] What feature should be implemented in PoDoFo?**
> 

Please make functions loadFromJpegInfo, exportToJpeg, loadFromJpeg, loadFromJpegData, loadFromTiffHandle, loadFromTiff, loadFromTiffData, loadFromPngHandle, loadFromPng, loadFromPngData of PDFImage public. 
Keeping them private is not protecting anything and making them public will not hurt anything and as long as the size of class has not changed, it will not cause and compatibility issues.

**Comment by ceztko** [comment]
I'm sorry, I thought I was clear in the other issue but I will repeat it here: I do not intend to make the internal functions public because it may be unsafe because of mismatches between the versions of TIFF/Jpeg/PNG library used to compile PoDoFo and the versions of the same libraries used by the consumer of the API. If you need to access some metadata in the images you can still do it in your user code and all libraries should give a "probe" functionality before actually doing the decoding of the pixel data, before feeding the same image data to `PdfImage::Load()` or `PdfImage::LoadFromBuffer()`. If you want to do some preprocessing of the image before loading it you can also set raw data of the image with an appropriate call of `PdfImage::SetDataRaw()` (see how it gets used in the implementation code of the various `loadFromJpeg`, `loadFromTiffHandle`, etc.).
