### ISSUE TITLE
How can I create spot color with a name?

### ISSUE THREAD

**Issue by a999dan** [podofo/podofo#187]
Thank you for your work and dedication. I have tried many times in a week without success. Is it still impossible to achieve?
I hope you can help me, I want to give up @.@ Where is the error in my code

`PoDoFo::PdfColor nPdfColor= PoDoFo::PdfColor(0.6, 0, 1, 0);
PoDoFo::PdfColorSpaceFilterSeparation* pPdfColorSpaceFilterPtr=new PoDoFo::PdfColorSpaceFilterSeparation("spot_1", color);
unique_ptr<PoDoFo::PdfColorSpace> PdfColorSpace = document.CreateColorSpace((PoDoFo::PdfColorSpaceFilterPtr)pPdfColorSpaceFilterPtr);
painter.GraphicsState.SetFillColorSpace(*PdfColorSpace);
painter.GraphicsState.SetFillColor(color);
painter.DrawRectangle(PoDoFo::Rect(nX, nY, nWidth, nHeight), PoDoFo::PdfPathDrawMode::Fill);
painter.FinishDrawing();
document.Save(ConvertGBKToUtf8(NewFilePath));`

**Comment by ceztko** [comment]
There was a bug in the export of the color space, caused by a recent rework/refactor ([link](https://sourceforge.net/p/podofo/mailman/message/58778530/) to the ML for description). I should have fixed it in https://github.com/podofo/podofo/commit/c87322d5bc970f890b8dd54a07d5efeda8ce4f2b , and I made also a [test](https://github.com/podofo/podofo/blob/0fd5b68a04a403a755f27b73c585c74b3586b69d/test/unit/ColorTest.cpp#L1600) for that based on your code, which at least it should restore the old functionalities that were in 0.9.x. To be honest, I don't have experience with non trivial custom/color spaces. You should inspect the stream of the page to tell me if the code is doing something useful or not, as the rendering of the page is blank.

**Comment by a999dan** [comment]
Thank you for your reply, but I still can‘t achieve what I want. I will describe my needs to see if there is a solution.
[spot_1.pdf](https://github.com/user-attachments/files/16722214/spot_1.pdf)
This is the spot color fill I want to achieve in the end. The spot color name is spot_1
Can you help me see how to achieve this?

**Comment by a999dan** [comment]
By the way, in the latest podofo-master code, is PDFNames not declared or there is some error, so it cannot be compiled?

**Comment by ceztko** [comment]
I looked at your PDF and I found a bug in the serialization of the cs/CS operators, now is fixed https://github.com/podofo/podofo/commit/57207ed2ddc12b38dc2d9d005539599e23a152be . The [test](https://github.com/podofo/podofo/blob/57207ed2ddc12b38dc2d9d005539599e23a152be/test/unit/ColorTest.cpp#L1599) now finally outputs something meaningful, but I honestly don't have the expertise to evaluate the current feature level of the PoDoFo API with regard to custom color spaces. For example your [spot_1.pdf](https://github.com/user-attachments/files/16722214/spot_1.pdf) has a `Separation` color space built with a `Lab` color, which I believe is something currently not possible in PoDoFo, but it could be added by extending the `PdfColorSpaceFilterSeparation` class. Please open a new ticket if you need a specific feature that you can describe concisely with PDF terminology.

> PDFNames not declared

You can find `PdfNames` by including `<podofo/optional/PdfNames.h>` which has a lot more names now. `PdfNames` is not used anymore inside PoDoFo, because you can conveniently create names faster with the `"DeviceRGB"_n` notation.
