### ISSUE TITLE
Something wrong with `PdfPainter::GetTextState().SetFontScale()`

### ISSUE THREAD

**Issue by igormironchik** [podofo/podofo#19]
In the following example as font scale changed, it will mess with another calls of `GetTextState().SetFontScale()`, and something horrible will be in the output. Maybe this is your new design, but in my point of view this is a mistake.

```cpp
#include <podofo/podofo.h>

using namespace PoDoFo;
using namespace std::literals;

int main()
{
	PdfMemDocument doc;

	PdfPainter painter;

	auto & page = doc.GetPages().CreatePage( PdfPage::CreateStandardPageSize( PdfPageSize::A4 ) );

	painter.SetCanvas( page );

	auto * font = doc.GetFonts().SearchFont( "Droid Serif" );

	painter.GetTextState().SetFont( *font, 10.0 );

	const auto str = "World"sv;

	PdfTextState st;
	st.FontSize = 10.0;
	st.RenderingMode = PdfTextRenderingMode::Fill;

	double x = 50, y = 50;

	painter.DrawText( "World World World", x, y * 2.0 );

	const auto l = font->GetStringLength( str, st );
	const auto s = font->GetStringLength( " ", st ) * 2.0;

	for( int i = 0; i < 3; ++i )
	{
		painter.DrawText( str, x, y );

		x += l;

		painter.GetTextState().SetFontScale( 2.0 );

		painter.DrawText( " ", x, y );

		x += s;

		painter.GetTextState().SetFontScale( 1.0 );
	}

	painter.FinishDrawing();

	doc.Save( "1.pdf" );

	return 0;
}
```

In the result:

![font_scale](https://user-images.githubusercontent.com/11455533/212601405-e9aaaab3-67a5-45e7-ad4c-201a11f053e4.png)

I really need to draw spaces "by hands" in my application with custom scale, word spacing in `PdfTextState` is not appropriate for me.

**Comment by ceztko** [comment]
```
	const auto l = font->GetStringLength( str, st );
	const auto s = font->GetStringLength( " ", st ) * 2.0;

	for( int i = 0; i < 3; ++i )
	{
                // ...
		x += l;
                // ...
		x += s;
```

You are using the stateless API where you manually pass the position coordinate and you do the advancing, as is in your code, and you are expecting it to work without re computing the string length after each update of the font scale, so I'm not surprised you will see something strange . You definitely should try the stateful API `BeginText`, `AddText`, `MoveTextPos`, `EndText`, which I'm not sure it will work since I am seeing it's not unit tested (I'm newly maintaining PoDoFo and I rewrote/reviewed a big part of it but I can't do miracles). I'm thankful you reported several bugs but in this case I'm expecting you to better do your homeworks. Try to rework your code so it will actually make a correct use of the API, which is similar to other rendering APIs you can find around, and if you find a clear bug please open a new ticket.
