### ISSUE TITLE
What `PdfTextRenderingMode` should do (+ missing strikeout/underline)?

### ISSUE THREAD

**Issue by igormironchik** [podofo/podofo#22]
I tried different text rendering modes, but see the difference only with `Fill` and `Stroke`.

In the following code

```cpp
painter.BeginText( 50, 750 );
painter.GetTextState().SetFont( *font, 24 );
painter.GetTextState().SetRenderingMode( PdfTextRenderingMode::Fill );
painter.AddText( "Hello World!!!" );
painter.EndText();
```

draws as regular font. Setting rendering mode to `Stroke` draws text a little bold, is it intended behavior?

What should do `FillStroke` mode? Now the text is invisible.

Is it possible to draw strikeout text? How, if so?

Thank you.

**Comment by ceztko** [comment]
> What should do FillStroke mode? Now the text is invisible.

This looks like a regression from 0.9.x, sorry for that. Please try https://github.com/podofo/podofo/commit/f729f23016399425f544485cf1a68efa23c21cf9 if it fixes for you.

> Is it possible to draw strikeout text? How, if so?

It was possible in 0.9.x, but got lost because the strikeout setting was part of `PdfFont`, and as I explained now this kind of settings can't stay there anymore. I remember this setting didn't fit as a state parameter, because it's not part of the PDF specification (literally the line of the strikeout is another draw command after the text), and I couldn't think of a better API at the time. The code to draw the line is still somewhere in the painter, but nobody calls it. Let's keep this issue open until a better API replacement is introduced (soon).

**Comment by igormironchik** [comment]
> This looks like a regression from 0.9.x, sorry for that. Please try [f729f23](https://github.com/podofo/podofo/commit/f729f23016399425f544485cf1a68efa23c21cf9) if it fixes for you.

I confirm that `FillStroke`, `Fill`, `Stroke` rendering methods work as expected now.

**Comment by ceztko** [comment]
I re-added a stateless API for drawing text strikeout/underlined https://github.com/podofo/podofo/commit/e92ff22ccf5a315e5dd863fa495fc96d3166edce. It's completely untested. I will probably test it within a week or two. If you want to have a look at it in the meanwhile.

**Comment by ceztko** [comment]
I actually tested strikeout/underline and they appear to work! I also added unit tests. But more important I did the promised review of `PdfPainter` API https://github.com/podofo/podofo/commit/c5a7c640062d88a7cdeaddad8a9d1002aa56c350, which now it makes much more sense to me, and I hope everything that was possible before should be possible now (except Add/DrawArc). For sure there are some new features. As usual with me, something is not greatly documented, but please ask me if you need clarifications.
