### ISSUE TITLE
Font is not added to XObject in Podofo v0.10.0

### ISSUE THREAD

**Issue by splashwizard** [podofo/podofo#228]
I've built a program which creates text with transformation there using XObject.
Here is the content of PDF I generated on 0.9.7
```31 0 obj
<<
/Type /XObject
/BBox [ 100.000000 200.000000 300.000000 250.000000 ]
/Filter /FlateDecode
/FormType 1
/Length 101
/Matrix [ 1 0 0 1 0 0 ]
/Resources <<
/Font <<
/Ft6 <<
/Type /Font
/BaseFont /Suruma
/Encoding /WinAnsiEncoding
/FirstChar 0
/FontDescriptor <<
/Type /FontDescriptor
/Ascent 667.000000
/CapHeight 667.000000
/Descent -333.000000
/Flags 32
/FontBBox [ -635.000000 -658.000000 1932.000000 677.000000 ]
/FontFile2 59 0 R
/FontName /Suruma
/ItalicAngle 0
/StemV 1
>>```

Here is the content of PDF I created using PoDoFo v0.10.4.

```31 0 obj
<</Type/XObject
/BBox[ 200 75 400 125]
/Filter/FlateDecode
/FormType 1
/Length 22
/Matrix[ 1 0 0 1 0 0]
/Resources
<</ProcSet
[
/PDF
/Text
/ImageB
/ImageC
/ImageI
]>>
/Subtype
/Form
>>```

How can I add Font to the XObject in PoDoFo 0.10.4? Please advise me the approach with code, thanks.

**Comment by ceztko** [comment]
No direct suggestions, because I have no idea how you are trying to add font resources to that XObject. The recommend approach is creating fonts through a `PdfPainter`, as you can add the XObject as a canvas with `PdfPainter::SetCanvas(xobj)`. Then you add a font to the painter with `PdfPainter::SetFont(font, size)`, that you previously created through a `PdfFontManager` instance you obtain from a document with `PdfDocument::GetFonts()`. The [helloworld](https://github.com/podofo/podofo/blob/0.10.x/examples/helloworld/helloworld.cpp) example shows the procedure with the only difference it set the page as a canvas, while you have to set the XObject.
