### ISSUE TITLE
Сonfusion of definitions SHARED_PODOFO / PODOFO_SHARED in basedefs.h

### ISSUE THREAD

**Issue by nntrifonov** [podofo/podofo#34]
Hi,

there are sereral checks on PODOFO_SHARED and SHARED_PODOFO in basedefs.h.
It seems that there is confusion in the definitions and on my mind SHARED_PODOFO should be changed to PODOFO_SHARED.
The same for PODOFO_STATIC.

**Comment by ceztko** [comment]
Thank you. There's also `STATIC_PODOFO` that looks wrong. I'm checking that now.

**Comment by nntrifonov** [comment]
Do you support -DPODOFO_STATIC=TRUE for cmake?

**Comment by ceztko** [comment]
Not really, but you can do `-DPODOFO_STATIC=FALSE`.  I I should probably just error immediately if PODOFO_STATIC is true externally, as I prefer to maintain a single variable. Feel free to try change my mind but you should be very convincing.

**Comment by ceztko** [comment]
Not really, but you can do -DPODOFO_SHARED=FALSE. I I should probably just error immediately if PODOFO_STATIC is true externally, as I prefer to maintain a single variable. Feel free to try change my mind but you should be very convincing.

**Comment by nntrifonov** [comment]
Well, I'll try)))

I did before -DPODOFO_STATIC=TRUE without -DPODOFO_SHARED=FALSE.  I need both options because I have several projects with shared and static link of libpodofo.

Before fix it builded and installed both shared and static libs well (except that it was necessary to copy podofo_private.a to /usr/lib for PODOFO_STATIC).

After the fix there is a problem with examples build, because now compiler checks PODOFO_STATIC and PODOFO_SHARED definition and shows the error message

    #error "Both PODOFO_SHARED and PODOFO_STATIC defined!"

IMHO it is a correct requirement to have an option for cmake with build and install both shared and static libs. And it works well except examples. 

Could you please fix cmake for examples?

**Comment by ceztko** [comment]
First thing to say: currently only one target is supported by decision, and that was my decision, also to simplify some messy decision making 0.9.x [code](https://github.com/podofo/podofo/blob/5723d09bbab68340a3a32923d90910c3d6912cdd/CMakeLists.txt#L52). It's not that your requirement is unreasonable, but not many projects will allow it, so let's think about it. First, was this really working with PoDoFo 0.9.x? Because that's what I see:

https://github.com/podofo/podofo/blob/5723d09bbab68340a3a32923d90910c3d6912cdd/src/podofo/CMakeLists.txt#L274

https://github.com/podofo/podofo/blob/5723d09bbab68340a3a32923d90910c3d6912cdd/src/podofo/CMakeLists.txt#L300

And that's set depending on `PODOFO_BUILD_SHARED` and `PODOFO_BUILD_STATIC` enablement, meaning that the single variable `PODOFO_DEPEND_TARGET` will be overwrote when both are enabled. Also in 0.9.x `PODOFO_BUILD_SHARED` will condition setting a general `PODOFO_CFLAGS`. In short, not the best things to do when wanting to support both targets in a clean way, especially because examples, tests and tools will end just pick one.

Anyway, let me know if 0.9.x was really allowing to build them at the same time. I may come up with a documented way to enable both targets (and these targets have their set of specialized `PODOFO_CLFAGS`/`PODOFO_DEPEND_TARGET`), but still the other variables will behave as only one target is the "main" one.

**Comment by ceztko** [comment]
> IMHO it is a correct requirement to have an option for cmake with build and install both shared and static libs

Believe me: it's hardcore to have such requirement in some cases, for example we have now a common `podofo-private` static library that:
1. Uses podofo library defined either by `podofo-shared` or `podofo-static`
2. Must be linked by either `podofo-shared` or `podofo-static`

I'm trying to see if it's possible to achieve to have both targets to compile, but because of no `podofo-private` no guarantees. If nothing works and I get tired, it's a no.

**Comment by ceztko** [comment]
I grew tired but I opened https://github.com/podofo/podofo/tree/experimental_dual_build to at least preserve the WIP: the idea is that externally one can manually enable targets with `PODOFO_BUILD_STATIC` or `PODOFO_BUILD_SHARED`, but one main target still exists, and that one is used by tests, examples, tools. I won't continue, because the `podofo-private` static library should be duplicated to make it work otherwise there will be linking problems, something like `podofo-private-shared` and `podofo-private-static` (but it would still be a static library in both cases). It's not hard to do, but I'm not interested now as I believe it's not worth. If you want to continue feel free, but I won't merge it unless it's very clean/easy to maintain/tested with the playground.
