### ISSUE TITLE
Let's discuss linking with `Conan` packages on MacOS

### ISSUE THREAD

**Issue by igormironchik** [podofo/podofo#36]
I did a research, and that what I found. In `Conan` everything is normal, if use all libraries from `Conan` everything is fine. The problem occurs when I want to use `Fontconfig` installed in system, and all other dependencies from `Conan`. `Fontconfig` from `Conan` useless, as it doesn't have system configuration files, it works, but with UI, Qt for example, it leads to use wrong fonts in the UI.

What happens on MacOS. When `CMake` found system `Fontconfig` it adds include directories where its headers are placed, usually this is `/usr/local/include`. And ops... There usually places `libjpeg` headers too. And `clang` compiles `PoDoFo` with system headers of `libjpeg`, that are version 80, but links to `Conan` `libjpeg`, that are version 90. And you know what then happens.

The same will be and with `vcpkg` on MacOS, if you will decide to use system `Fontconfig`.

And I'm in struggle... What should I do?

**Comment by ceztko** [comment]
Clashes are clashes. If the search is known to be ambiguous, then you have the option to alter the fontconfig search by setting `Fontconfig_INCLUDE_DIR` externally in your build.

**Comment by igormironchik** [comment]
> Clashes are clashes. If the search is known to be ambiguous, then you have the option to alter the fontconfig search by setting `Fontconfig_INCLUDE_DIR` externally in your build.

No, you a little misunderstood. `CMake` do everything right, it found system `Fontconfig` and all other dependecnies installed by `Conan`. But compiler do wrong things - to him set `-I` options with folders where `Fontconfig` includes, `Conan` packages includes, a lot of paths to look for includes. And as `Fontconfig` requires system include path like `/url/local/include`, `clang` includes `#include <jpeglib.h>` from `/usr/local/include`, and not from `Conan` include path for `libjpeg`.

**Comment by ceztko** [comment]
Ah, now I see, I never tried, but there's an option in CMAKE [`include_directories`](https://cmake.org/cmake/help/latest/command/include_directories.html) to include folders before system paths (probably including `/url/local/include`). Also you could risk doing it by default for all includes with [`CMAKE_INCLUDE_DIRECTORIES_BEFORE`](https://cmake.org/cmake/help/latest/variable/CMAKE_INCLUDE_DIRECTORIES_BEFORE.html#variable:CMAKE_INCLUDE_DIRECTORIES_BEFORE), since it's a controlled build.

**Comment by igormironchik** [comment]
`CMAKE_INCLUDE_DIRECTORIES_BEFORE` doesn't work in this case. I don't see a possibility to solve this MacOS specific problem beautifully. So doesn't matter. I will use `brew` to install dependencies on MacOS, and that's all. Thank you.

**Comment by ceztko** [comment]
If it was just for testing maybe you could try if uninstalling brew `libjpeg` works, but in general I think it's best to use packages just from one package manager.

> `Fontconfig` from `Conan` useless

That's strange: fontconfig is not a component of macos, so I use it by supplying a [fallback](https://github.com/podofo/podofo/blob/0199136705d839a511ca566d672ecf0d37b0e192/src/podofo/main/PdfFontConfigWrapper.cpp#L137) configuration that is loaded as the default unless a global configuration is already found loaded. Because of this I would expect the brew/Conan fontconfig to behave similarly, unless you are doing early initialization of fonconfig or my assumptions are somewhat wrong. It would require more investigations but this is very low priority for me.

I'm attaching `fonts.conf` as found on my system after fontconfig brew installation for reference:
[fonts.conf.txt](https://github.com/podofo/podofo/files/10537096/fonts.conf.txt)

**Comment by igormironchik** [comment]
In case of `PoDoFo` `Fontconfig` installed by `Conan` or `brew` will behave the same. But if you develop GUI application with `Qt` and link `Qt` libraries and `PoDoFo` that linked with `Fontconfig` from `Conan` it can lead to wrong fonts in the GUI, whereas `PoDoFo` will work as expected. This is the only reason why I wanted to link with system's `Fontconfig`. On Linux the behavior such is 100%. I'm not sure about MacOS. If anybody will decide to build my application on MacOS with `Conan`, I'm ready to listen him and do research in this way. But now I stopped to investigate this question. Thanks.

This is not an issue for `PoDoFo`, it will work as expected with `Fontconfig` from any package manager.
