### ISSUE TITLE
Use of undeclared identifier 'OSSL_LIB_CTX_new'

### ISSUE THREAD

**Issue by skillsfactory** [podofo/podofo#54]
Hi,

I'm trying to compile PoDoFo but when the compiler build the PdfEncrypt.cpp file (both from Unix Makefiles and Xcode) I get this error: **Use of undeclared identifier 'OSSL_LIB_CTX_new'**
I've installed OpenSSL3 with libcrypto, fontconfig, freetype, jpeg, tiff and lua

The OS is MacOS 13.2.1 x86_64

What I have to do?
Maybe I miss some libraries?

Thanks
Luca

**Comment by ceztko** [comment]
Some missing information here, but I am assuming you are attempting to build master. PoDoFo is known to be OpenSSL3 compatible and I just modified the [MacOs CI](https://github.com/podofo/podofo/blob/master/.github/workflows/build-mac.yml) to build with OpenSSL 3 from brew instead of 1.1, and it [works](https://github.com/podofo/podofo/actions/runs/4251160892/jobs/7393156447). If you are using other package managers, or building from sources dependencies, you may be on your own since you are assumed to be able to identify and fix clash/mismatch issues that may arise in your system.

**Comment by skillsfactory** [comment]
Ok thank you,
I’ll try

**Comment by ceztko** [comment]
I updated the Readme with a [guide](https://github.com/podofo/podofo#build-with-brew) on how to build with brew. I am assuming you either fixed or know how to continue on your own.

**Comment by skillsfactory** [comment]
I've solved thanks
