### ISSUE TITLE
The new PdfMetadata class in 0.10.0 breaks various use cases

### ISSUE THREAD

**Issue by kovidgoyal** [podofo/podofo#75]
The new PdfMetadata class tries to unify Info and XML metadata handling. This is a bad idea. It means that trying to set custom metadata properties in XMP metadata is no longer possible because the metadata class always overwrites the XMP metadata unconditionally. The only workaround I have found is to disable updating of the modified date when saving the PDF and manually managing the Info and XML objects.

Also relatedly, there is no way to get the PDF version without initializing the metadata object, I suggest making GetPdfVersion in PdfDocument public instead of protected. Given that PdfMemDocument is marked as final, its the only way to get this information without invoking PdfMetadata.

**Comment by ceztko** [comment]
I understand your unease but one of the aims for the new course for PoDoFo was to make it a [PDF/A](https://en.wikipedia.org/wiki/PDF/A) preserving manipulation library. As such, unifying `/Info` and `/Metadata` is a reasonable approach and it's behaviorally the same that happens when manipulating the metadata with Adobe Acrobat so I believe this should stay the default behavior. I also analyzed Acrobat to match its behavior when manipulating the metadata with the `PdfMetadata` class. So said, we should reason what you are trying to achieve: please post your original `/Metadata` and describe how you want to manipulate it.  We could define flags that overrides the default automatic handling of `/Info` and `/Metadata`, or we could add API interface to plug your custom metadata into XMP, hoping this can be done without supplying a full XML manipulation interface.

> Also relatedly, there is no way to get the PDF version without initializing the metadata object.

The actual initialization of `PdfMetadata`, with reading of the `/Metadata` and normalization of the XMP, happens only when [`PdfMetadata::ensureInitialized()`](https://github.com/podofo/podofo/blob/c3ddafe1d37df0a08dba80644760f99ea4f28285/src/podofo/main/PdfMetadata.cpp#L328) is called, which shouldn't be issued when just retrieving the version with [`PdfMetadata::GetPdfVersion()`](https://github.com/podofo/podofo/blob/c3ddafe1d37df0a08dba80644760f99ea4f28285/src/podofo/main/PdfMetadata.cpp#L249). `PdfMetadata` was designed as an abstraction where to group all regular PDF metadata, so that's why the access is protected in `PdfDocument`. I currently believe this doesn't require changes and maybe you inadvertently called other `PdfMetadata` methods before asking for the version.

**Comment by kovidgoyal** [comment]
On Sun, May 14, 2023 at 01:18:49AM -0700, Francesco Pretto wrote:
> I understand your unease but one of the aims for the new course for PoDoFo was to make it a [PDF/A](https://en.wikipedia.org/wiki/PDF/A) preserving manipulation library. As such, unifying `/Info` and `/Metadata` is a reasonable approach and it's behaviorally the same that happens when manipulating the metadata with Adobe Acrobat so I believe this should stay the default behavior. I also analyzed Acrobat to match its behavior when manipulating the metadata with the `PdfMetadata` class. So said, we should reason what you are trying to achieve: please post your original `/Metadata` and describe how you want to manipulate it.  We could define flags that overrides the default automatic handling of `/Info` and `/Metadata`, or we could add API interface to plug your custom metadata into XMP, hoping this can be done without supplying a full XML manipulation interface.

I store custom properties in the XMP block, specific to my application.
So I need to be able to manipulate it independently of the /Info dict.
Basically I need PoDoFo to not write its own XMP packet when updating
metadata. I can achieve that currently by bypassing PdfMetadata
completely and writing my own code for manipulating the /Info and
/Metadata dicts. In addition I have to avoid triggerring podofo from
writing the XMP packet. So far in my use case, just passing the save
option to not update modified date is sufficient.

> 
> > Also relatedly, there is no way to get the PDF version without initializing the metadata object.
> 
> The actual initialization of `PdfMetadata`, with reading of the `/Metadata` and normalization of the XMP, happens only when [`PdfMetadata::ensureInitialized()`](https://github.com/podofo/podofo/blob/c3ddafe1d37df0a08dba80644760f99ea4f28285/src/podofo/main/PdfMetadata.cpp#L328) is called, which shouldn't be issued when just retrieving the version with [`PdfMetadata::GetPdfVersion()`](https://github.com/podofo/podofo/blob/c3ddafe1d37df0a08dba80644760f99ea4f28285/src/podofo/main/PdfMetadata.cpp#L249). `PdfMetadata` was designed as an abstraction where to group all regular PDF metadata, so that's why the access is protected in `PdfDocument`. I currently believe this doesn't require changes and maybe you inadvertently called other `PdfMetadata` methods before asking for the version.

OK, I will test more thoroughly. I did not trace all the code paths as I
am not that familiar with PoDoFo internals.

**Comment by kovidgoyal** [comment]
OK I tested that currently at least reading the version does not trigger podofo to write xmp metadata.

**Comment by ceztko** [comment]
> I store custom properties in the XMP block, specific to my application. So I need to be able to manipulate it independently of the /Info dict. Basically I need PoDoFo to not write its own XMP packet when updating metadata. I can achieve that currently by bypassing PdfMetadata completely and writing my own code for manipulating the /Info and /Metadata dicts. In addition I have to avoid triggerring podofo from writing the XMP packet.

Well, consider that the current handling has some XMP related advantages:
- It keeps the `/Info` and XMP properties in `/Metadata` synced. This is a requirement for PDF/A;
- It performs a normalization of the XMP packet as suggested by [ISO 16684-2:2014](https://www.iso.org/standard/57422.html).

If you show me the original sample XMP packet (or state if it's blank) and the result you want to end with I could consider adding an API to set custom elements to the XMP, without altering the officially supported PDF properties.

> So far in my use case, just passing the save option to not update modified date is sufficient.

In your case of course you can certainly workaround the issue not updating the modification date at all when saving, which will skip syncing the XMP as result. But a custom flag like `PdfSaveOptions::NoSyncXMP` (to implement) would better fit your use case and still perform the `/Info` update normally.

**Comment by kovidgoyal** [comment]
On Sun, May 14, 2023 at 09:57:06AM -0700, Francesco Pretto wrote:
> > I store custom properties in the XMP block, specific to my application. So I need to be able to manipulate it independently of the /Info dict. Basically I need PoDoFo to not write its own XMP packet when updating metadata. I can achieve that currently by bypassing PdfMetadata completely and writing my own code for manipulating the /Info and /Metadata dicts. In addition I have to avoid triggerring podofo from writing the XMP packet.
> 
> Well, consider that the current handling has some XMP related advantages:
> - It keeps the `/Info` and XMP properties in `/Metadata` synced. This is a requirement for PDF/A;
> - It performs a normalization of the XMP packet as suggested by [ISO 16684-2:2014](https://www.iso.org/standard/57422.html).
> 
> If you show me the original sample XMP packet (or state if it's blank) and the result you want to end with I could consider adding an API to set custom elements to the XMP, without altering the officially supported PDF properties.

I need to read the original XML, merge my custom properties while not
deleting any existing custom properties in the XML, and then write out
the result.

The code also follows the spec recommended algorithm of comparing the
mod dates in the info and xmp blocks before deciding which type of
metadata to prefer when reading effective metadata.

If you want to see the code that does it, here it is:
https://github.com/kovidgoyal/calibre/blob/master/src/calibre/ebooks/metadata/xmp.py

If would prefer to leave this logic in python rather than have to
re-implement it in C++, since python is much better at this sort of
thing.

> 
> > So far in my use case, just passing the save option to not update modified date is sufficient.
> 
> In your case of course you can certainly workaround the issue not updating the modification date at all when saving, which will skip syncing the XMP as result. But a custom flag like `PdfSaveOptions::NoSyncXMP` (to implement) would better fit your use case and still perform the `/Info` update normally.

Yes, a dedicated save option to not touch the XMP metadata would be
preferable for me.

-- 
_____________________________________

Dr. Kovid Goyal 
https://www.kovidgoyal.net
https://calibre-ebook.com
_____________________________________

**Comment by ceztko** [comment]
I thought about this issue and I am not sure exactly how you to deal with it. You discovered that `PdfSaveOptions::NoModifyDateUpdate` is an effective workaround for you: now, adding an `PdfSaveOptions::NoSyncXMP` as I was suggesting may be more confusing, since blocking all metadata touching would require setting multiple flags, that is inconvenient. Also this would still break the "recommendation" that the update of `/Info` and `/Metadata` should happen at once. At the moment I think the best solution is really just use `PdfSaveOptions::NoModifyDateUpdate` for your use case. Maybe we could rename it to something like `PdfSaveOptions::NoUpdateMetadata` (and keep the previous enum entry for compatibility), where with `Metadata` we really mean both `/Info` and `/Metadata`, and make it more clear in the documentation what happens during document save (which at the moment updates `/Info/ModDate` and normalize/sync all properties in `/Metadata`).

I'm open to suggestions on how to proceeded.

**Comment by kovidgoyal** [comment]
I think having a flag/option that tells podofo "dont update metadata" is fine. There is no confusion with dont update modification time, they serve different purposes. Add a note to the documentation of dont update modification time that if dont update metadata is set modification time is not updated. And yes the flag should apply to both Info and XMP metadata.

**Comment by ceztko** [comment]
I am not sure I explain myself very well. What I was suggesting is really editing `PdfSaveOptions` as it follows:

```
enum class PdfSaveOptions
{
    None = 0,
    _Reserved1 = 1,
    _Reserved2 = 2,
    NoFlateCompress = 4,
    NoCollectGarbage = 8,
    /**
     * Don't update the trailer "/Info/ModDate" with current time and synchronize XMP metadata "/Catalog/Metadata"
     */
    NoUpdateMetadata = 16,
    Clean = 32,

    /**
      * \deprecated Use NoUpdateMetadata instead
      */
    NoModifyDateUpdate = NoUpdateMetadata 
};
```

So basically what your doing would be already correct and I'm just better reflecting it in the API. The alternative is really decoupling the synchronization of `/Info` and `/Metadata` from the modification date update, but it's not something I really want to encourage. But maybe it's not that terrible...what would be for you the best solution?

**Comment by kovidgoyal** [comment]
OK that is fine for me.

**Comment by ceztko** [comment]
Done the change in https://github.com/podofo/podofo/commit/96689eb6e45b71eae1577ecb2d4a796c52e9a813
