### ISSUE TITLE
Regression: Fails to operate with font the svn version works just fine

### ISSUE THREAD

**Issue by mcrha** [podofo/podofo#77]
The version at commit c3ddafe1d37df0a08dba80644760f99ea4f28285 fails to operate with 
[this font](https://github.com/podofo/podofo/files/11506962/3OF9.TTF.zip), while the svn at revision 2020, or even at revision 2063 has absolutely no problem with this font.

My test was to copy this font file (unzipped) into `~/.local/share/fonts/` and then modify the `helloworld` example to use `3Of9Barcode` font instead. The font information is properly printed, it only fails on drawing with it, with error:

```
PoDoFo encountered an error. Error: 31PdfErrorCode::InvalidFontData	Error Description: The font data is invalid.	Callstack:	#0 Error Source : main/PdfEncoding.cpp: 82		Information: The provided string can't be converted to CID encoding
```

**Comment by ceztko** [comment]
Please show an example of using the font that fails.

**Comment by mcrha** [comment]
> Please show an example of using the font that fails.

```diff
diff --git a/examples/helloworld/helloworld.cpp b/examples/helloworld/helloworld.cpp
index e1e265d1..1942f9e5 100644
--- a/examples/helloworld/helloworld.cpp
+++ b/examples/helloworld/helloworld.cpp
@@ -63,7 +63,7 @@ void HelloWorld(const string_view& filename)
         // PDF file. If Arial is not available, a default font will be used.
         // 
         // The created PdfFont will be deleted by the PdfDocument.
-        font = document.GetFonts().SearchFont("Arial");
+        font = document.GetFonts().SearchFont("3Of9Barcode");
 
         // If the PdfFont object cannot be allocated return an error.
         if (font == nullptr)
```

aka just use it in the helloworld example.

**Comment by ceztko** [comment]
I investigated the issue a little: basically I believe that if it was working in 0.9.x that happened accidentally. Basically now when converting a string to CIDs we are really checking for the existence of a Unicode map, and we try to map each Unicode code point to a CID accordingly to that map.  If the Unicode map is missing the code uses a strategy that was present also in 0.9.x and try to determine if the font is a symbol font by searching for a [`FT_ENCODING_MS_SYMBOL`](https://freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_encoding_ms_symbol) "encoding", and if it is present we try to offset the code point to a code in the "Private Use Area" range, in the same way as it was done in [0.9.x](https://github.com/podofo/podofo/blob/5723d09bbab68340a3a32923d90910c3d6912cdd/src/podofo/doc/PdfFontMetricsFreetype.cpp#L418). The rationale for this is following the Microsoft [guideline](https://learn.microsoft.com/en-us/typography/opentype/spec/recom#non-standard-symbol-fonts) for non standard/symbol fonts (basically fonts that have characters out of conventional historic characters sets). This is a guess on my side, but possibly this was done to encode strings using these fonts with "weird" character codes. The font "3Of9Barcode" has a `FT_ENCODING_MS_SYMBOL` charmap but it's not a symbol font, because it doesn't have the first byte of [PANOSE](https://learn.microsoft.com/en-us/typography/opentype/spec/recom#panose-values) set to '5' in OS/2 TrueType table, as also required by Microsoft guidelines for symbol fonts. This means we should probably ignore the `FT_ENCODING_MS_SYMBOL` charmap and try to use the other `FT_ENCODING_APPLE_ROMAN` map  which your font appears to have. We would still miss a map from Unicode to the Apple latin/roman charset, but that's not terribly hard to add. In this way we can continue use this font conventionally directly converting Unicode/UTF-8 strings (which are now first citizen in PoDoFo). We should then use `FT_ENCODING_MS_SYMBOL` map only when the font is really a symbol font as specified by the PANOSE value, or not use it at all if there are usable alternatives.

**Comment by mcrha** [comment]
[This change](https://github.com/podofo/podofo/files/11652290/podofo.patch.txt) fixes it for me, but I'm not sure how much valid change it is, especially whether it could break any current fonts and/or usages.

On the other hand, considering using WinAnsi encoding works as expected, I'm wondering whether the ` | 0xf000` is the right thing to do. The other font metrics do not do this, which means one or the other is wrong, no?

**Comment by ceztko** [comment]
I have in mind a more elaborated fix that will skip loading the `FT_ENCODING_MS_SYMBOL` when possible (as in most cases, including yours), specially since there's not a single "symbol" charset. If there are other latin like charset maps available those can be used instead. Also it could be useful to offer a way to index glyphs as they appear on the font, so one is able to select glyphs that don't have Unicode code point.

**Comment by ceztko** [comment]
It took some time but I implemented the fix as I wanted. Basically for non symbol fonts (as yours) I can recover an Unicode to GID map from FreeType legacy encodings/charmaps. Instead, for symbol/non standard fonts I do interpret the Unicode code point as the character code in the "encoding" with a 1:1 mapping. It works for Symbol/Wingdings fonts and seems to do exactly as in Adobe Acrobat.
